name: Automation Workflow
on:
  workflow_run:
    workflows: ["Development Workflow"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean test -Dbrowser=chrome -Denvvalue=test
      continue-on-error: true

    - name: Archive and upload Extent Report
      uses: actions/upload-artifact@v2
      with:
        name: extent-report
        path: report/page.html
